services:

  postgres:
    container_name: aws-refresh
    image: postgres:17.5
    environment:
      - POSTGRES_DB=aws-refresh
      - POSTGRES_USER=psqladmin
      - POSTGRES_PASSWORD=psqladminpas$
    ports:
      - 7433:5432
